name = "iglympics-do"
main = "worker/do/index.ts"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "SCOREBOARD_DO"
class_name = "ScoreboardDO"

[[durable_objects.bindings]]
name = "CHESS_GAME_DO"
class_name = "ChessGameDO"

[[durable_objects.bindings]]
name = "RACING_GAME_DO"
class_name = "RacingGameDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ScoreboardDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ChessGameDO"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["RacingGameDO"]
