name = "iglympics-do"
main = "worker/do/index.ts"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "SCOREBOARD_DO"
class_name = "ScoreboardDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ScoreboardDO"]
